# Generated by Django 4.1.7 on 2023-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=15)),
                ('state', models.CharField(max_length=255)),
                ('types', models.CharField(default='Student', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=15)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('types', models.CharField(default='Teacher', max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('types', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
