# Generated by Django 4.1.7 on 2023-03-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quesmodel_remove_questions_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
