# Generated by Django 3.0.5 on 2023-03-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
